#!/usr/bin/perl

use 5.14.2;
use strict;
use warnings;

my %has_occured;

# A little obfuscation here...
while (<>) {
    for (split) {
        if (not defined $has_occured{$_}) {
            $has_occured{$_} = 1;
            print;
            print ' ';
        }
    }

    print "\n";
}
